kcommunity:
  default: ''
  textarea: false
  description:
    en: "Maintained only as an illustration. Switching to using JSON in the Header Div, instead."

# settings.yml - update CSP
extend_content_security_policy_script_src:
  type: list
  default: "https://empowercdn.com|https://kune.co|https://flow.kune.co|https://myflow.kune.co"
 
